In [5]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import re
from geopy.geocoders import Nominatim
import pickle
import os
import wikipedia

In [8]:
cd ..

c:\Users\Lenovo\Desktop\Tourist Attraction Recommendation System

c:\Users\Lenovo\Desktop\Tourist Attraction Recommendation System\venv\Lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [9]:
df = pd.read_csv("Dataset/attractions_nepal.csv")

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           421 non-null    int64
 1   name         421 non-null    object
 2   address      421 non-null    object
 3   latitude     421 non-null    float64
 4   longitude    421 non-null    float64
 5   rating       420 non-null    float64
 6   second_word  421 non-null    object
 7   types        421 non-null    object
dtypes: float64(3), int64(1), object(4)
memory usage: 26.4+ KB

In [11]:
df.head()

,id,name,address,latitude,longitude,rating,second_word,types
0,1,Garden of Dreams,"P877+MR2, Tridevi Sadak, Kathmandu 44600, Nepal",27.714126,85.314504,4.2,Tridevi Sadak,"tourist_attraction, park, point_of_interest, e..."
1,2,Swayambhu Buddha Park - Ring Road,"Kathmandu 44600, Nepal",27.716145,85.283887,4.5,Nepal,"park, tourist_attraction, point_of_interest, e..."
2,3,Narayanhiti Royal Palace,"Narayanhiti Path, Kathmandu 44600, Nepal",27.714822,85.318084,4.4,Kathmandu 44600,"museum, point_of_interest, establishment"
3,4,Kathmandu Guide,"Paknajol Marg, Kathmandu 44600, Nepal",27.717224,85.309096,4.0,Kathmandu 44600,"tourist_attraction, museum, hindu_temple, trav..."
4,15,Ratna Park,"रत्न पार्क पथ, Kathmandu 44600, Nepal",27.706053,85.314808,3.9,Kathmandu 44600,"park, tourist_attraction, point_of_interest, e..."

In [32]:
# def extract_coordinates(text):
#     # First pattern: Standard decimal coordinates
#     standard_pattern = r"([-+]?\d*\.\d+|\d+\.?\d*),\s*([-+]?\d*\.\d+|\d+\.?\d*)"
#     # Second pattern: Coordinates with symbols and directions
#     directional_pattern = r"([-+]?\d*\.\d+|\d+\.?\d*)°?\s*([NSEW])?,\s*([-+]?\d*\.\d+|\d+\.?\d*)°?\s*([NSEW])?"

#     # Try matching the standard format
#     match = re.search(standard_pattern, text)
#     if match:
#         return float(match.group(1)), float(match.group(2))

#     # Try matching the directional format
#     match = re.search(directional_pattern, text)
#     if match:
#         lat = float(match.group(1)) * (-1 if match.group(2) in ['S', 'W'] else 1)
#         lon = float(match.group(3)) * (-1 if match.group(4) in ['S', 'W'] else 1)
#         return lat, lon

#     # If no match, return None
#     return None, None

In [ ]:
# def extract_coordinates(text):
#     loc = Nominatim(user_agent="GetLoc")
#     getLoc = loc.geocode(text)
#     if getLoc is None:
#         return None, None
#     latitude = getLoc.latitude
#     longitude = getLoc.longitude
#     return latitude, longitude

In [7]:
longitudes = []
latitudes = []

In [8]:
# Remove square brackets and split into two columns
df[['Longitude', 'Latitude']] = df['location'].str.strip('[]').str.split(',', expand=True)

# Convert columns to float for numerical operations
df['Longitude'] = df['Longitude'].astype(float)
df['Latitude'] = df['Latitude'].astype(float)

In [ ]:
# for text in df.iloc[200:325]['Name']:
#     latitude, longitude = extract_coordinates(text)
#     if latitude and longitude != None:
#         print(f"Latitude: {latitude}")
#         latitudes.append(latitude)
#         print(f"Longitude: {longitude}")
#         longitudes.append(longitude)

#     else:
#         print("No coordinates found in the text.")
#         latitudes.append(None)
#         longitudes.append(None)

Latitude: 34.215635
Longitude: 75.5038297
Latitude: 34.0565625
Longitude: 77.66673866189419
Latitude: 34.27885241508465
Longitude: 77.85108865583163
No coordinates found in the text.
No coordinates found in the text.
Latitude: 33.56737645
Longitude: 75.98018289870282
Latitude: 33.66391575
Longitude: 77.35041371147784
No coordinates found in the text.
Latitude: 19.7959051
Longitude: -155.335383
Latitude: 34.2786625
Longitude: 77.6046891
Latitude: 34.0565625
Longitude: 77.66673866189419
Latitude: 27.57208885
Longitude: 77.67203795263097
Latitude: 21.6413358
Longitude: 69.601032
Latitude: 23.2309668
Longitude: 82.1334207
Latitude: 27.650136699999997
Longitude: 77.37313377826086
Latitude: 26.99490135
Longitude: 88.28533056378379
Latitude: 26.68477385
Longitude: 89.30471768931005
No coordinates found in the text.
Latitude: 21.61792835
Longitude: 87.50711642476077
No coordinates found in the text.
No coordinates found in the text.
No coordinates found in the text.
Latitude: 26.7474882
Longitude: 88.81458592463328
No coordinates found in the text.
No coordinates found in the text.
Latitude: 23.31688845
Longitude: 85.28180377943092
Latitude: 29.6323214
Longitude: 79.61456305384945
Latitude: 20.238369
Longitude: 85.83371903751328
No coordinates found in the text.
Latitude: 20.48527625
Longitude: 85.86501293344713
Latitude: 21.549243099999998
Longitude: 83.90112859444788
Latitude: 19.68531945
Longitude: 85.25036993144289
Latitude: 19.4888247
Longitude: 84.8991907
No coordinates found in the text.
No coordinates found in the text.
No coordinates found in the text.
Latitude: 13.053275150000001
Longitude: 80.28328873013857
Latitude: 9.9195433
Longitude: 78.1188334260622
Latitude: 9.2880968
Longitude: 79.3173756426647
Latitude: 8.0783202
Longitude: 77.5549562
Latitude: 11.40341705
Longitude: 76.69167888165407
No coordinates found in the text.
Latitude: 10.234003000000001
Longitude: 77.48652291657108
Latitude: 10.78257995
Longitude: 79.13138188923924
No coordinates found in the text.
Latitude: 11.7832744
Longitude: 78.21046871339286
Latitude: 8.7284759
Longitude: 77.68895103182844
Latitude: 12.81972
Longitude: 79.70944
Latitude: 16.5153429
Longitude: 80.6058743
No coordinates found in the text.
Latitude: 17.39608405
Longitude: 78.5244837245757
No coordinates found in the text.
Latitude: 13.8031581
Longitude: 77.6097474
Latitude: 15.102175
Longitude: 78.1116692
Latitude: 9.6255941
Longitude: 77.1644806
Latitude: 16.30690105
Longitude: 80.51362085375354
Latitude: 14.8133184
Longitude: 78.2874575
Latitude: 14.16586875
Longitude: 77.80776249890566
Latitude: 17.766316699999997
Longitude: 83.25052449743701
Latitude: 13.3903362
Longitude: 78.0256818
Latitude: 2.2109244500000003
Longitude: 102.19729381393157
Latitude: 18.2939056
Longitude: 83.0597306
Latitude: 53.9599168
Longitude: -1.0895447
Latitude: 17.7672009
Longitude: 83.3485108306389
Latitude: 17.7128522
Longitude: 83.31990582899448
Latitude: 17.72082665
Longitude: 83.33382069350534
Latitude: 27.3868289
Longitude: 88.8308961
Latitude: 27.30536295
Longitude: 88.25145084208097
Latitude: 27.6227125
Longitude: 85.31799053635206
Latitude: 27.28875815
Longitude: 88.56142002291666
Latitude: 17.912316
Longitude: 102.76500938671434
Latitude: 27.36587555
Longitude: 88.83788926315745
Latitude: 27.374530749999998
Longitude: 88.76197985870488
Latitude: 26.165107
Longitude: 91.7059298
Latitude: 26.65810465
Longitude: 93.39274406257059
Latitude: 26.19648555
Longitude: 91.74499488423024
No coordinates found in the text.
Latitude: 27.012901499999998
Longitude: 94.27468538142726
Latitude: 26.7227946
Longitude: 90.97788799238984
Latitude: 26.2429185
Longitude: 91.52653500420408
Latitude: 26.259400550000002
Longitude: 91.98476799961671
Latitude: 27.586609099999997
Longitude: 91.8573902
Latitude: 23.83698675
Longitude: 91.28275067020547
Latitude: 23.47363145
Longitude: 91.83818815074817
No coordinates found in the text.
No coordinates found in the text.
Latitude: 25.55167505434516
Longitude: 94.12167855797173
Latitude: 11.9321674
Longitude: 79.8360554
Latitude: 12.0073927
Longitude: 79.8099471
Latitude: -38.192086
Longitude: 147.42110203084178
Latitude: 11.67444565
Longitude: 92.74778558292749
Latitude: 11.9826676
Longitude: 92.95707831459254
Latitude: 11.8379008
Longitude: 93.02964449635024
Latitude: -17.7627609
Longitude: 178.4061134
Latitude: 20.7109607
Longitude: 70.980783
Latitude: 20.4073978
Longitude: 72.8324448
No coordinates found in the text.
Latitude: 23.378112864504732
Longitude: 85.31197227496848
Latitude: 24.69593025
Longitude: 84.99139027981707
No coordinates found in the text.
No coordinates found in the text.
No coordinates found in the text.
Latitude: 28.46812985
Longitude: 77.06912641367134
Latitude: 28.5412453
Longitude: 77.15510822535421
No coordinates found in the text.
Latitude: 28.6280479
Longitude: 77.2093211
Latitude: 30.7345609
Longitude: 79.0673204
Latitude: 28.5674442
Longitude: 77.32112402627533
Latitude: 28.4526337
Longitude: 77.5262656
Latitude: 10.0267542
Longitude: 76.39177723537276
Latitude: 20.397733549999998
Longitude: 85.81386331046137
Latitude: 13.010962750000001
Longitude: 77.55522393851444
Latitude: 17.43455455
Longitude: 78.38669818623289
Latitude: 28.6506822
Longitude: 77.23296096363757
Latitude: 9.2880968
Longitude: 79.3173756426647
Latitude: 28.3492531
Longitude: 77.53700501165349
Latitude: 26.8087716
Longitude: 81.01279288413409
Latitude: 10.02721845
Longitude: 76.30788730187876
Latitude: 28.584726769893308
Longitude: 77.1811827202923
Latitude: 25.2130828
Longitude: 91.676736
Latitude: 28.61251665
Longitude: 77.27731839825316
Latitude: 27.1798258
Longitude: 78.02082227320588
Latitude: 24.85725455
Longitude: 79.92448692274795
Latitude: 26.926209649999997
Longitude: 75.82383458642204
Latitude: 26.91169265
Longitude: 75.81950236387307

In [ ]:
len(latitudes)

0

In [21]:
# Function to get description from Wikipedia with error handling
def get_description(place_name):
    try:
        # Attempt to get the exact page summary
        summary = wikipedia.summary(place_name, sentences=3)
        print(f"Description found for {place_name}")
        return summary
    except wikipedia.exceptions.DisambiguationError as e:
        # Handle disambiguation: Return first option from the suggestions
        return "error"
    except wikipedia.exceptions.HTTPTimeoutError:
        return "error"
    except wikipedia.exceptions.PageError:
        # Suggest a better title or handle page not found
        try:
            # Try with auto-suggest for a more accurate match
            suggestions = wikipedia.search(place_name)
            if suggestions:
                return wikipedia.summary(suggestions[0], sentences=3)
            else:
                return "error"
        except Exception as ex:
            return "error"

In [22]:
descriptions = []

In [23]:
for name in df['name']:
    description = get_description(name)
    if description != None and description != "error":
        descriptions.append(description)
    else:
        print(f"Description not found for {name}")
        descriptions.append(None)

Description found for Garden of Dreams
Description found for Swayambhu Buddha Park - Ring Road
Description found for Narayanhiti Royal Palace
Description found for Kathmandu Guide
Description found for Ratna Park
Description not found for छतिकोट दरबार-बाजुरा
Description found for Nag Pokhari
Description not found for National Art Museum
Description not found for मयुर झ्याल
Description found for Bhaktapur Art Gallery
Description found for Wood Carving Museum
Description found for Kamal pokhari
Description found for Elephant Breeding Center
Description found for Shey Phoksundo National Park
Description found for Gorkha Museum
Description not found for Gorkha Palace
Description not found for Bhaludhunga Religious Tourism Ecological Park
Description found for National Museum of Nepal
Description found for Bhandarkhal Jungle
Description found for Kathmandu Fun Park
Description found for Patan Museum
Description found for Parsa National Park
Description not found for Puspalal Birth Place, Ramechhap
Description found for Hem Narayan Park
Description not found for Taksar Bazar टक्सार बजार
Description found for Sindhuligadi Memorial Park
Description found for Birendra Aishwarya Park
Description not found for Baglung Municipality-2, Purano Bus park, Yashora Park
Description found for Rudra lake Baglung Nepal
Description not found for १००००० लिटरको पानी टंकी
Description not found for Rudraman Gurung Memorial Park(रुद्रमान गुरुङ स्मृतिपार्क
Description not found for Farmers Father DevDhawal Park
Description not found for सल्लेनी पाखा सामुदायिक बन
Description found for Bhimpokhara
Description not found for Sansaarkot संसारकोट तितौरे
Description not found for मंगलेको डाँडा
Description not found for UK KRISHI TATHA PASHUPANCHI FARM
Description not found for Sahid Smriti Park DHAULAGIRI BAGLUNG
Description found for B.P. Smriti Park
Description found for Kripa
Description found for Hariyali park
Description not found for Ismriti prak
Description not found for Mannaya, Dhimi
Description found for Aashish thapa
Description not found for Sansaarkot संसारकोट
Description not found for Maire khola jharana (Waterfall)
Description found for Banke National Park
Description not found for Inacho ईनाचो
Description not found for गणेश चौतारी Ganesh Choutari
Description not found for Bhoula pukhu
Description not found for Jhaukhel pipal boat झाैखेल पिपल बाेट
Description found for Jagat Sundar Statue
Description found for Single Bar
Description found for Temple park
Description found for Pipalbot
Description found for Changu Narayan
Description found for फुलबारी
Description not found for Gamcha Pipal Bot
Description found for sallaghari
Description not found for Suchana tole
Description not found for Baniya Danda Naya Basti
Description found for Rabin homes
Description not found for Itapako, taralan chok
Description found for tenge
Description not found for Bagmara
Description found for जरायोटार
Description found for Mahendra park
Description found for Magar Bari
Description found for Bar Danda
Description not found for Dawan चौक
Description not found for Ramailo Dada (Aakash Memorial)
Description not found for Balaute बलौटे बजार
Description found for Halhale
Description not found for Bantawa Niwas
Description not found for Khamare Dobato
Description not found for Chhimalung
Description found for Spring water source
Description not found for Balaute Bhanjyang
Description found for Wild Adventure Resort
Description found for Sarang Wildlife Sanctuary
Description not found for Dhanushadham Protected Forest
Description not found for Dhanushadham Botanical Garden
Description not found for Tinkune Park Dharapani
Description not found for Jugeshwarpur, Tree Place
Description found for Jehovah Intersection
Description not found for डाँडा टोल चोक धनुषा
Description found for Dolpo Buddha Hotel
Description not found for The Gurkhaz Rock Garden & Stone Park (Love Park)
Description found for Children Park
Description not found for Dumsheree Gorkha
Description not found for चिया बारी
Description not found for Love Danda, Ilam
Description found for New Zealand Park
Description found for Workout Park
Description found for B. P. Park
Description not found for Statue of Martyr Ratna Kumar Bantawa Rai
Description found for Sukilumba Park
Description found for Tea garden view hand
Description not found for Barhabise masar,ilam
Description not found for Shrastha Park
Description not found for Bisauni Dhunga
Description not found for Nar Bahadur Samarung's Tea garden
Description not found for Deurali
Description not found for Padam kanta's tea garden 🏡
Description not found for Statue of Martyr Bam Prasad Bantawa
Description found for Rajbanshi tol
Description not found for देवरीया वनस्पति उध्यान कैलाली
Description not found for सुन्तला बगैचा(घरखेडा)🍊
Description not found for Khadgaun vokunday,kaskikot, Nepal
Description found for Sankhamul Park
Description not found for Madan Bhandari Smriti Vatika
Description found for BUDDHA PARK Boudhanath
Description found for Suryamukhi Park
Description found for Balaju Park
Description found for Buddha park
Description found for Kamal Pokhari Park
Description found for Jump KTM Indoor Trampoline Park
Description not found for Switzerland Park Aloknagar
Description not found for Raniban Park
Description not found for Khusibu Children Park
Description not found for Bhurungkhel Green Park
Description not found for Children’s Park
Description not found for Apple Ground Public Park Narephat
Description found for Shanti Park
Description found for Bhadrakali park
Description not found for Pushpalal Memorial Park
Description not found for Kripalu Udhyan
Description found for Shanti Park
Description found for Mitra Park
Description not found for Kumari Chaur Park
Description not found for The Handigaun Triangle (dhungedhara) park
Description not found for Janamaitri Park (Pepsicola Town Plan)
Description not found for Sahayoginagar Park
Description found for Earthquake Memorial park
Description not found for Ranibari Community Forest
Description not found for Bancharetar Chowk (बन्चरे टार चोक)
Description found for Whoopee Land Amusement Water Park
Description not found for Ghyoi Lisang Peace Park
Description not found for Setopool Park
Description not found for Dharahara Park धरहरा बगैचा
Description not found for Nepal Rastra Bank Sworna Jayanti Park
Description found for Pasupatinath forest
Description found for pashupatinath park
Description found for khotang bazar
Description found for UN Park
Description not found for Yaualakhel Park
Description found for Jawalakhel Park
Description not found for Kusunti Height, Bista Pakha Park
Description found for Manmohan Park
Description not found for Syosyo Hajurba Chowk Park
Description not found for Guita Open Garden
Description not found for Duniya Danda Green Park
Description found for Lalitpur Metro Park
Description found for Sahid Smarak Park
Description found for Safal Park
Description not found for Jwagal Children Park / Jwagala Machakhya
Description found for Butterfly square
Description not found for Imadol, Bhojhepokhari
Description not found for Shovahiti(ढुङ्गेधारा)
Description not found for Bagdole Batika
Description not found for dadathok park
Description not found for Park बगैँचा
Description not found for Gagan Batika, Nagbahal
Description not found for Patan Dhoka Chautara (चौतारी)
Description not found for Park बगैँचा
Description found for Pocket park
Description not found for Park बगैचा
Description not found for Hattiban
Description not found for Park
Description found for Playground Park
Description not found for Imukhel Bal Udhyan
Description not found for Children’s park
Description not found for Lamochaur Jhamsikhel Park
Description not found for Jhanakhya Metro Park झनाख्यः मेत्रो पार्क
Description not found for Shant Vawan Uddhan
Description found for RN Joshi Museum / Park Gallery
Description found for Public Fitness Park
Description found for Mahalaxmisthan
Description not found for Ganeshman Singh Park गणेशमान सिंह पार्क
Description found for Small park
Description found for Khusi The Happiness
Description found for lagankhel
Description found for King Birendra Circle Statue
Description not found for Ookhar Bot, sitapakha, Lalitpur
Description not found for Ji Swā Chuka
Description not found for Dhadkhola
Description not found for Martyr Rudra Pakhrin Memorial Park
Description not found for Nachai
Description found for Milarepa Memorial Park
Description found for Thorang peak
Description not found for Thorang La Pass
Description found for Gangapurna Lookout
Description not found for Blue Lake
Description not found for Dendi Sherpa Lookout Point
Description not found for Balbahadur statue
Description not found for BHUSUNE JUNGLE
Description not found for HILEPANI हिलेपानी
Description found for Hariyali Park
Description not found for बाइसधारा मुल (Baaisdhara Mul)
Description not found for बजेनी
Description not found for चर्के पिङ चौतारा
Description not found for Sahid Smirti Park, Gajuri
Description found for Ganesh Mandir Park
Description not found for Bhalabang
Description not found for Chautara juction
Description not found for सोमरे धारा
Description not found for Pratikshya laye
Description not found for Rattari
Description not found for धाईरे
Description found for Gajuri
Description found for द्वार खोला
Description found for Mallarani
Description not found for Damti suspension bridge
Description not found for BITAR RASAM PARK बिटार रासम पार्क
Description not found for Thulaghar danda park ठुलाघरडाँडा पार्क
Description not found for madhya pahadi lokmarga-Dahoo
Description not found for Udayanarayan Smriti Park(उदयनारायण स्मृति पार्क)
Description not found for गौतम कुमार हायू
Description not found for यात्रु प्रतिक्षालय मन्थलि
Description not found for Salle
Description not found for Damakur
Description not found for Tamri
Description not found for Suryapura chok,Rupandehi,Tilottama-8
Description not found for Childern Park
Description not found for Dahipauri
Description not found for Siraha
Description not found for No one
Description not found for Lauwa pokhari
Description not found for Thenghi clean water State deep Boring
Description not found for Nahar Singh syaraha
Description not found for Gauri shankar krishi farm.khairtoka
Description found for Dilip home
Description found for Mahisotha
Description not found for ROMAN RONY HOME 🏠
Description not found for Torpee toll
Description found for naresh home
Description found for portaha village
Description not found for Maidan Sataun
Description not found for Upper Bhujunge 360° view point
Description not found for BP Smirti Pratikshalaya(balti more)
Description not found for Macchang waterfall
Description not found for DD Park Tanahunsur
Description found for Kanchenjunga Conservation Area
Description not found for ghaprakharka झाप्राखर्क मालिका
Description not found for Lamgau garden house
Description found for Shree Nepal forest
Description not found for दिवा विश्राम स्थल
Description not found for अर्धनारेशोवर गोठाटार पार्क
Description not found for Finear Art Gallery
Description found for Kathmandu Art House
Description found for Siddhartha Art Gallery
Description found for Universal Art Gallery
Description found for Buddha Nepal Art Gallery
Description not found for Takpa Gallery, lazimpat
Description found for Arts Nepal Gallery - Art Gallery in Nepal
Description found for Freedom Art Gallery
Description found for BK ART Gallery
Description found for Nupur Art Gallery Center Pvt. Ltd.
Description found for Swoyambhu Art Gallery
Description not found for Mithila Yain Art Gallery
Description found for Himalayan Arts/Thangka Gallery
Description found for Shangri-La Art Gallery
Description found for Woodcraft Gallery
Description found for Everest Art Gallery
Description found for Artudio
Description not found for Tiny Art Gallery Thamel
Description found for The Art Gallery Cafe
Description found for Kumari Gift & Art Gallery
Description not found for Nabin Art Creation, New Buspark
Description found for THE HIMALAYAN ART GALLERY
Description found for 21st century art gallery
Description not found for Rincheling Thanka Gallery and Art School
Description found for New Himalayan Art Gallery
Description found for Art Nepal
Description found for Atelier 2 Fine Art Gallery
Description not found for Lapis Thanka & Art Gallery Shop
Description found for LA gallery
Description found for Reva Art Gallery
Description found for The Spiritual Arts
Description found for Classic gallery
Description found for Dipak Art Gallery
Description found for AS Handicrafts & Art Gallery
Description found for Himalayan Art Gallery Jhamsikhel
Description found for ADVENTURE ART GALLERY
Description found for Mithila Things Art gallery
Description found for ART DECOR
Description found for Gallery of Creatives
Description found for Gallery Station
Description found for Brush Strokes Art Gallery
Description found for The Idyllic Paintings
Description not found for Nuwakot 3D Art Museum
Description found for Sachin Art Gallery
Description found for Chitra Nepal
Description found for Shrestha Art Gallery
Description found for Art of Nepalaya
Description found for Arjun Nepali Arghakhanchi
Description not found for Shree Shreedharacharya Saligram Museum
Description not found for हिलियापानी धारो
Description not found for कुमलेको पहरो
Description found for Brass and Bronze Museum
Description not found for Falaicha Art,Culture And Museum Stay
Description not found for सहिद अजबलाल ऐसमारक
Description found for Taragaon Next
Description found for The City Museum Kathmandu
Description found for Aviation Museum
Description found for Military Museum
Description found for Birendra Museum
Description found for Tribhuvan Museum
Description found for Natural History Museum
Description found for Shree Sadan
Description found for RICH museum of Craft and Design
Description found for Limbu Museum
Description not found for दुपाःत्वाः पुखुसि फल्चा ( Phukhusi Phalcha )
Description not found for TIBETAN SINGINGBOWL CENTER
Description not found for Dhalachhen
Description found for Khukuri house gallery
Description found for NIRVANA THANGKA GALLERY
Description not found for Gyanlal Handcraft
Description found for Nepalese Crafts Pvt. Ltd.
Description not found for इतिहास हस्तकला
Description found for Bodhisattva International
Description found for Adi Buddha Handicraft
Description not found for The Unique Handicraft अनुपम हस्तकला
Description not found for Satyamohan Joshi Loksahitya Sangrahalaya
Description found for Gautam Gift Emporium
Description not found for Pwasya Metal Craft
Description found for Ashoka Handicrafts
Description not found for Seolee Handicraft
Description found for Manang Culture Museum
Description not found for Shiv Temple Lalparsa Ghat
Description found for single mango tree
Description not found for Tarakhase pokhari
Description found for Sindhuli Gadhi War Museum
Description not found for Bindash dj (Bali yadav)
Description found for Everest Science Center Nepal
Description found for Central Zoo
Description not found for Golfutar Sunrise Point
Description found for Nepal Trek Hub
Description found for By Mountain People | unlock your next trekking adventure
Description not found for Sandakpur View Tower
Description found for Maitighar Mandala
Description found for Shahid Dharma Bhakta Statue
Description not found for Bakhetro Samabeshi Bakhra Utpadan Firm
Description found for Nepal Wildlife Resort Pvt Ltd
Description found for Zebra House

In [24]:
df['Description'] = descriptions

In [25]:
df.head()

,id,name,address,latitude,longitude,rating,second_word,types,Description
0,1,Garden of Dreams,"P877+MR2, Tridevi Sadak, Kathmandu 44600, Nepal",27.714126,85.314504,4.2,Tridevi Sadak,"tourist_attraction, park, point_of_interest, e...","The Garden of Dreams (Nepali:स्वप्न बगैंचा, Ne..."
1,2,Swayambhu Buddha Park - Ring Road,"Kathmandu 44600, Nepal",27.716145,85.283887,4.5,Nepal,"park, tourist_attraction, point_of_interest, e...","Vesak (Pali: Vesākha; Sanskrit: vaiśākha), als..."
2,3,Narayanhiti Royal Palace,"Narayanhiti Path, Kathmandu 44600, Nepal",27.714822,85.318084,4.4,Kathmandu 44600,"museum, point_of_interest, establishment",The Narayanhiti Palace Museum (Nepali: नारायणह...
3,4,Kathmandu Guide,"Paknajol Marg, Kathmandu 44600, Nepal",27.717224,85.309096,4.0,Kathmandu 44600,"tourist_attraction, museum, hindu_temple, trav...",The Kathmandu Valley (Nepali: काठमाडौं उपत्यका...
4,15,Ratna Park,"रत्न पार्क पथ, Kathmandu 44600, Nepal",27.706053,85.314808,3.9,Kathmandu 44600,"park, tourist_attraction, point_of_interest, e...",Ratna Park is a park and surrounding district ...

In [40]:
# Define the Pickle file path
pickle_file = 'coordinates.pkl'

# Check if the Pickle file exists
if os.path.exists(pickle_file):
    # If file exists, load existing data and append the new data
    with open(pickle_file, 'rb') as file:
        existing_latitudes, existing_longitudes = pickle.load(file)
    
    # Append new data to the existing lists
    existing_latitudes.extend(latitudes)
    existing_longitudes.extend(longitudes)
    
    # Save the updated lists back to the Pickle file
    with open(pickle_file, 'wb') as file:
        pickle.dump((existing_latitudes, existing_longitudes), file)
else:
    # If file does not exist, create it and save the new data
    with open(pickle_file, 'wb') as file:
        pickle.dump((latitudes, longitudes), file)

print("Data has been appended to 'coordinates.pkl'")

Data has been appended to 'coordinates.pkl'

In [41]:
# Load data from the Pickle file
with open('coordinates.pkl', 'rb') as file:
    latitudes, longitudes = pickle.load(file)
# Print the extracted data
print("Latitudes:", len(latitudes))
print("Longitudes:", len(longitudes))

Latitudes: 325
Longitudes: 325

In [42]:
df['latitude'] = latitudes
df['longitude'] = longitudes

In [44]:
def generate_description(row):
    entrance_fee = "free" if row['Entrance Fee in INR'] == 0 else f"₹{row['Entrance Fee in INR']}"
    dslr_info = "DSLR cameras are allowed" if row['DSLR Allowed'] == "Yes" else "DSLR cameras are not allowed"
    
    description = (
        f"{row['Name']} is a renowned {row['Type']} located in the {row['Zone']} zone of {row['State']}, {row['City']}. "
        f"Established in {row['Establishment Year']}, it holds {row['Significance']} significance. "
        f"It is rated {row['Google review rating']} stars on Google, with approximately {row['Number of google review in lakhs']} lakh reviews. "
        f"Visitors typically spend around {row['time needed to visit in hrs']} hours exploring this site. "
        f"The entrance fee is {entrance_fee}, and {dslr_info}. "
        f"The best time to visit is during the {row['Best Time to visit']}."
    )
    return description

In [45]:
# Generate descriptions and add them to the DataFrame
df["Description"] = df.apply(generate_description, axis=1)

# Display the descriptions
print(df["Description"])

0      India Gate is a renowned War Memorial located ...
1      Humayun's Tomb is a renowned Tomb located in t...
2      Akshardham Temple is a renowned Temple located...
3      Waste to Wonder Park is a renowned Theme Park ...
4      Jantar Mantar is a renowned Observatory locate...
                             ...
320    Akshardham is a renowned Temple located in the...
321    Agra Fort is a renowned Fort located in the Ce...
322    Madhya Pradesh Tribal Museum is a renowned Mus...
323    City Palace is a renowned Palace located in th...
324    Albert Hall Museum is a renowned Museum locate...
Name: Description, Length: 325, dtype: object

In [14]:
df['country'] = ['Nepal'] * 349
# df['category'] = ['Hiking Trails'] * len(longitudes)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 349 entries, 0 to 348
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            348 non-null    float64
 1   Unnamed: 1    0 non-null      float64
 2   Unnamed: 2    0 non-null      float64
 3   locationName  348 non-null    object
 4   address       348 non-null    object
 5   location      348 non-null    object
 6   description   331 non-null    object
 7   Each          347 non-null    object
 8   Category      348 non-null    object
 9   Unnamed: 9    0 non-null      float64
 10  Longitude     348 non-null    float64
 11  Latitude      348 non-null    float64
 12  country       349 non-null    object
dtypes: float64(6), object(7)
memory usage: 35.6+ KB

In [15]:
filtered_df = df[['locationName', 'description', 'Longitude', 'Latitude','Category', 'country']]
filtered_df.head()

,locationName,description,Longitude,Latitude,Category,country
0,Betana Wetland,"The Betana Wetland Area, also known as Betana ...",87.432068,26.659276,Natural Landmark,Nepal
1,wakupati narayan,wakupati narayan temple suited at Bhaktapur su...,85.437087,27.673386,Religious Site,Nepal
2,kushma Bungee,jump,83.674621,28.223402,Tourist Attraction,Nepal
3,Gadhimai Temple,Gadhimai temple is the temple of the goddess G...,85.047285,26.993407,Religious Site,Nepal
4,Thupten Monastery,Thupten Choling Monastery is the well-known la...,86.549282,27.606160,Religious Site,Nepal

In [16]:
filtered_df.columns = ['name','description', 'longitude', 'latitude', 'category','country'] 
filtered_df

,name,description,longitude,latitude,category,country
0,Betana Wetland,"The Betana Wetland Area, also known as Betana ...",87.432068,26.659276,Natural Landmark,Nepal
1,wakupati narayan,wakupati narayan temple suited at Bhaktapur su...,85.437087,27.673386,Religious Site,Nepal
2,kushma Bungee,jump,83.674621,28.223402,Tourist Attraction,Nepal
3,Gadhimai Temple,Gadhimai temple is the temple of the goddess G...,85.047285,26.993407,Religious Site,Nepal
4,Thupten Monastery,Thupten Choling Monastery is the well-known la...,86.549282,27.606160,Religious Site,Nepal
...,...,...,...,...,...,...
344,IchhaKamana Mandir,"The Ichchhakamana Temple, located in the north...",84.624813,27.871427,Religious Site,Nepal
345,Shree Satya Narayan Mandir,"Shree Satya Narayan Mandir, located in Biratna...",87.281623,26.461582,Religious Site,Nepal
346,Taleju Bhawani Temple,"The magnificent Taleju temple, located in Durb...",85.308046,27.704915,Religious Site,Nepal
347,Jalbire Jharna,"Jalbire, a picturesque village nestled in the ...",84.527304,27.824569,Natural Landmark,Nepal
348,NaN,NaN,NaN,NaN,NaN,Nepal

In [17]:
print(filtered_df['longitude'].isnull().sum())
print(filtered_df['longitude'].isnull().sum())

1
1

In [ ]:
# Function to extract the first part of the string before the semicolon or colon
def extract_first_part(text):
    # Split by both semicolon and colon, and return the first part
    return text.split(';')[0].split(':')[0]

# Apply the function to the 'name' column and create a new column 'extracted_name'
filtered_df['name'] = filtered_df['name'].apply(extract_first_part)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4164\3071754169.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['name'] = filtered_df['name'].apply(extract_first_part)

In [53]:
print(f"Number of unique countries: {filtered_df['country'].nunique()}")

Number of unique countries: 1

In [19]:
filtered_df = filtered_df.dropna(subset=['latitude','longitude','description'])
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 331 entries, 0 to 347
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         331 non-null    object
 1   description  331 non-null    object
 2   longitude    331 non-null    float64
 3   latitude     331 non-null    float64
 4   category     331 non-null    object
 5   country      331 non-null    object
dtypes: float64(2), object(4)
memory usage: 18.1+ KB

In [ ]:
# df= df.groupby('country')['name'].nunique()
# df

In [ ]:
asian_countries = [
    "Afghanistan", "Armenia", "Azerbaijan", "Bahrain", "Bangladesh", "Bhutan",
    "Brunei", "Cambodia", "China", "Cyprus", "Georgia", "India", "Indonesia",
    "Iran", "Iraq", "Israel", "Japan", "Jordan", "Kazakhstan", "Kuwait",
    "Kyrgyzstan", "Laos", "Lebanon", "Malaysia", "Maldives", "Mongolia",
    "Myanmar (Burma)", "Nepal", "North Korea", "Oman", "Pakistan", "Palestine",
    "Philippines", "Qatar", "Saudi Arabia", "Singapore", "South Korea",
    "Sri Lanka", "Syria", "Tajikistan", "Thailand", "Timor-Leste", "Turkey",
    "Turkmenistan", "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen"
]

In [ ]:
len(asian_countries)

48

In [ ]:
filtered_df = filtered_df[filtered_df['country'].isin(asian_countries)]
filtered_df.head()

,name,description,longitude,latitude,category,country
0,Maligaun hiking trail,"Maligaun Viewpoint, located at an elevation of...",85.443946,27.641183,Hiking Trails,Nepal
1,"A short hike to Doleshwor Mahadev temple, Bhak...",Doleshwor Mahadev temple hike is also a warmin...,85.438449,27.638809,Hiking Trails,Nepal
2,Ranikot hike,Ranikot: a blend of nature and adventure\nRani...,85.427528,27.624751,Hiking Trails,Nepal
3,Stepping out from Nagarkot to Changunarayan,Since Bhaktapur lies within the territory of t...,85.518265,27.716509,Hiking Trails,Nepal
4,Pilot Baba Hike,"On the very south of Bhaktapur city, in betwee...",85.422573,27.640425,Hiking Trails,Nepal

In [20]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 331 entries, 0 to 347
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         331 non-null    object
 1   description  331 non-null    object
 2   longitude    331 non-null    float64
 3   latitude     331 non-null    float64
 4   category     331 non-null    object
 5   country      331 non-null    object
dtypes: float64(2), object(4)
memory usage: 18.1+ KB

In [27]:
# grouped_df= filtered_df.groupby('country')['name'].nunique(
df.to_csv('nepal_attraction_with_description.csv')

In [29]:
df.tail()

,id,name,address,latitude,longitude,rating,second_word,types,Description
416,737,Maitighar Mandala,"M8VC+R5R, Kathmandu 44600, Nepal",27.694469,85.320317,4.2,Kathmandu 44600,"park, point_of_interest, establishment",The Maitighar Mandala (Nepali: माइतीघर मण्डला)...
417,746,Shahid Dharma Bhakta Statue,"P86Q+VG7, Kathmandu 44600, Nepal",27.712156,85.338788,4.0,Kathmandu 44600,"park, point_of_interest, establishment",Dharma Bhakta Mathema (1909—1941) was a profes...
418,761,Bakhetro Samabeshi Bakhra Utpadan Firm,"Dudesota khola Dang, Ghorahi 22400, Nepal",28.057621,82.473410,5.0,Ghorahi 22400,"zoo, point_of_interest, establishment",None
419,763,Nepal Wildlife Resort Pvt Ltd,"2nd Floor bhagbanbahal, Kathmandu 44600, Nepal",27.715390,85.312329,4.3,Kathmandu 44600,"zoo, park, point_of_interest, establishment",Nagarahole National Park is a national park lo...
420,764,Zebra House,"M9Q5+45J, Kathmandu 44600, Nepal",27.687829,85.357882,3.0,Kathmandu 44600,"zoo, point_of_interest, establishment",The Zebra Puzzle is a well-known logic puzzle....